version: '3'
services:

  server:
    container_name: server
    build: .
    volumes:
      - ./server:/data
    ports:
      - "8081:8081"

  client:
    container_name: client
    build: .
    volumes:
      - ./client:/data
    ports:
      - "8080:8080"
    depends_on:
      - server